package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.22

import (
	"context"

	"github.com/aws/aws-sdk-go-v2/aws"
	"github.com/sheacloud/tfom/internal/graph/generated"
	"github.com/sheacloud/tfom/pkg/models"
)

// ModuleAssignment is the resolver for the moduleAssignment field.
func (r *applyExecutionRequestResolver) ModuleAssignment(ctx context.Context, obj *models.ApplyExecutionRequest) (*models.ModuleAssignment, error) {
	return r.apiClient.GetModuleAssignmentBatched(ctx, obj.ModuleAssignmentId)
}

// InitOutput is the resolver for the initOutput field.
func (r *applyExecutionRequestResolver) InitOutput(ctx context.Context, obj *models.ApplyExecutionRequest) (*string, error) {
	if obj.InitOutputKey == nil {
		return nil, nil
	}
	output, err := r.apiClient.DownloadResultObject(ctx, *obj.InitOutputKey)
	if err != nil {
		return nil, err
	}
	outputString := string(output)
	return &outputString, nil
}

// ApplyOutput is the resolver for the applyOutput field.
func (r *applyExecutionRequestResolver) ApplyOutput(ctx context.Context, obj *models.ApplyExecutionRequest) (*string, error) {
	if obj.ApplyOutputKey == nil {
		return nil, nil
	}
	output, err := r.apiClient.DownloadResultObject(ctx, *obj.ApplyOutputKey)
	if err != nil {
		return nil, err
	}
	outputString := string(output)
	return &outputString, nil
}

// ApplyExecutionRequest is the resolver for the applyExecutionRequest field.
func (r *queryResolver) ApplyExecutionRequest(ctx context.Context, applyExecutionRequestID string) (*models.ApplyExecutionRequest, error) {
	return r.apiClient.GetApplyExecutionRequest(ctx, applyExecutionRequestID)
}

// ApplyExecutionRequests is the resolver for the applyExecutionRequests field.
func (r *queryResolver) ApplyExecutionRequests(ctx context.Context, limit *int, nextCursor *string) (*models.ApplyExecutionRequests, error) {
	if limit == nil {
		limit = aws.Int(100)
	}

	return r.apiClient.GetApplyExecutionRequests(ctx, int32(*limit), aws.ToString(nextCursor))
}

// ApplyExecutionRequest returns generated.ApplyExecutionRequestResolver implementation.
func (r *Resolver) ApplyExecutionRequest() generated.ApplyExecutionRequestResolver {
	return &applyExecutionRequestResolver{r}
}

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type applyExecutionRequestResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
