package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.22

import (
	"context"

	"github.com/sheacloud/tfom/internal/graph/generated"
	"github.com/sheacloud/tfom/pkg/models"
)

// ModuleAssignment is the resolver for the moduleAssignment field.
func (r *applyExecutionRequestResolver) ModuleAssignment(ctx context.Context, obj *models.ApplyExecutionRequest) (*models.ModuleAssignment, error) {
	return r.apiClient.GetModuleAssignmentBatched(ctx, obj.ModuleAssignmentID)
}

// InitOutput is the resolver for the initOutput field.
func (r *applyExecutionRequestResolver) InitOutput(ctx context.Context, obj *models.ApplyExecutionRequest) (*string, error) {
	response := string(obj.InitOutput)
	return &response, nil
}

// ApplyOutput is the resolver for the applyOutput field.
func (r *applyExecutionRequestResolver) ApplyOutput(ctx context.Context, obj *models.ApplyExecutionRequest) (*string, error) {
	response := string(obj.ApplyOutput)
	return &response, nil
}

// ApplyExecutionRequest is the resolver for the applyExecutionRequest field.
func (r *queryResolver) ApplyExecutionRequest(ctx context.Context, applyExecutionRequestID uint) (*models.ApplyExecutionRequest, error) {
	return r.apiClient.GetApplyExecutionRequest(ctx, applyExecutionRequestID)
}

// ApplyExecutionRequest returns generated.ApplyExecutionRequestResolver implementation.
func (r *Resolver) ApplyExecutionRequest() generated.ApplyExecutionRequestResolver {
	return &applyExecutionRequestResolver{r}
}

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type applyExecutionRequestResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
