package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.22

import (
	"context"

	"github.com/aws/aws-sdk-go-v2/aws"
	"github.com/sheacloud/tfom/internal/graph/generated"
	"github.com/sheacloud/tfom/pkg/models"
)

// TerraformDriftCheckWorkflowRequests is the resolver for the terraformDriftCheckWorkflowRequests field.
func (r *modulePropagationDriftCheckRequestResolver) TerraformDriftCheckWorkflowRequests(ctx context.Context, obj *models.ModulePropagationDriftCheckRequest, limit *int, nextCursor *string) (*models.TerraformDriftCheckWorkflowRequests, error) {
	if limit == nil {
		limit = aws.Int(100)
	}

	return r.apiClient.GetTerraformDriftCheckWorkflowRequestsByModulePropagationDriftCheckRequestId(ctx, obj.ModulePropagationDriftCheckRequestId, int32(*limit), aws.ToString(nextCursor))
}

// CreateModulePropagationDriftCheckRequest is the resolver for the createModulePropagationDriftCheckRequest field.
func (r *mutationResolver) CreateModulePropagationDriftCheckRequest(ctx context.Context, modulePropagationDriftCheckRequest models.NewModulePropagationDriftCheckRequest) (*models.ModulePropagationDriftCheckRequest, error) {
	return r.apiClient.PutModulePropagationDriftCheckRequest(ctx, &modulePropagationDriftCheckRequest)
}

// ModulePropagationDriftCheckRequest is the resolver for the modulePropagationDriftCheckRequest field.
func (r *queryResolver) ModulePropagationDriftCheckRequest(ctx context.Context, modulePropagationID string, modulePropagationDriftCheckRequestID string) (*models.ModulePropagationDriftCheckRequest, error) {
	return r.apiClient.GetModulePropagationDriftCheckRequest(ctx, modulePropagationID, modulePropagationDriftCheckRequestID)
}

// ModulePropagationDriftCheckRequests is the resolver for the modulePropagationDriftCheckRequests field.
func (r *queryResolver) ModulePropagationDriftCheckRequests(ctx context.Context, limit *int, nextCursor *string) (*models.ModulePropagationDriftCheckRequests, error) {
	if limit == nil {
		limit = aws.Int(100)
	}

	return r.apiClient.GetModulePropagationDriftCheckRequests(ctx, int32(*limit), aws.ToString(nextCursor))
}

// ModulePropagationDriftCheckRequest returns generated.ModulePropagationDriftCheckRequestResolver implementation.
func (r *Resolver) ModulePropagationDriftCheckRequest() generated.ModulePropagationDriftCheckRequestResolver {
	return &modulePropagationDriftCheckRequestResolver{r}
}

type modulePropagationDriftCheckRequestResolver struct{ *Resolver }
