package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.22

import (
	"context"

	"github.com/aws/aws-sdk-go-v2/aws"
	"github.com/sheacloud/tfom/internal/graph/generated"
	"github.com/sheacloud/tfom/pkg/models"
)

// ModuleAccountAssociation is the resolver for the moduleAccountAssociation field.
func (r *queryResolver) ModuleAccountAssociation(ctx context.Context, modulePropagationID string, moduleAccountAssociationID string) (*models.ModuleAccountAssociation, error) {
	return r.apiClient.GetModuleAccountAssociation(ctx, modulePropagationID, moduleAccountAssociationID)
}

// ModuleAccountAssociations is the resolver for the moduleAccountAssociations field.
func (r *queryResolver) ModuleAccountAssociations(ctx context.Context, limit *int, nextCursor *string) (*models.ModuleAccountAssociations, error) {
	if limit == nil {
		limit = aws.Int(100)
	}

	return r.apiClient.GetModuleAccountAssociations(ctx, int32(*limit), aws.ToString(nextCursor))
}

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
