package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.22

import (
	"context"

	"github.com/aws/aws-sdk-go-v2/aws"
	"github.com/sheacloud/tfom/internal/graph/generated"
	"github.com/sheacloud/tfom/pkg/models"
)

// ModuleAccountAssociations is the resolver for the moduleAccountAssociations field.
func (r *modulePropagationResolver) ModuleAccountAssociations(ctx context.Context, obj *models.ModulePropagation, limit *int, nextCursor *string) (*models.ModuleAccountAssociations, error) {
	if limit == nil {
		limit = aws.Int(100)
	}

	return r.apiClient.GetModuleAccountAssociationsByModulePropagationId(ctx, obj.ModulePropagationId, int32(*limit), aws.ToString(nextCursor))
}

// CreateModulePropagation is the resolver for the createModulePropagation field.
func (r *mutationResolver) CreateModulePropagation(ctx context.Context, modulePropagation models.NewModulePropagation) (*models.ModulePropagation, error) {
	return r.apiClient.PutModulePropagation(ctx, &modulePropagation)
}

// DeleteModulePropagation is the resolver for the deleteModulePropagation field.
func (r *mutationResolver) DeleteModulePropagation(ctx context.Context, modulePropagationID string) (bool, error) {
	err := r.apiClient.DeleteModulePropagation(ctx, modulePropagationID)
	return err == nil, err
}

// ModulePropagation is the resolver for the modulePropagation field.
func (r *queryResolver) ModulePropagation(ctx context.Context, modulePropagationID string) (*models.ModulePropagation, error) {
	return r.apiClient.GetModulePropagation(ctx, modulePropagationID)
}

// ModulePropagations is the resolver for the modulePropagations field.
func (r *queryResolver) ModulePropagations(ctx context.Context, limit *int, nextCursor *string) (*models.ModulePropagations, error) {
	if limit == nil {
		limit = aws.Int(100)
	}

	return r.apiClient.GetModulePropagations(ctx, int32(*limit), aws.ToString(nextCursor))
}

// ModulePropagation returns generated.ModulePropagationResolver implementation.
func (r *Resolver) ModulePropagation() generated.ModulePropagationResolver {
	return &modulePropagationResolver{r}
}

type modulePropagationResolver struct{ *Resolver }
