package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.22

import (
	"context"

	"github.com/samtekinc/fourcee/internal/graph/generated"
	"github.com/samtekinc/fourcee/pkg/models"
)

// ModuleVersion is the resolver for the moduleVersion field.
func (r *modulePropagationResolver) ModuleVersion(ctx context.Context, obj *models.ModulePropagation) (*models.ModuleVersion, error) {
	return r.apiClient.GetModuleVersionBatched(ctx, obj.ModuleVersionID)
}

// ModuleGroup is the resolver for the moduleGroup field.
func (r *modulePropagationResolver) ModuleGroup(ctx context.Context, obj *models.ModulePropagation) (*models.ModuleGroup, error) {
	return r.apiClient.GetModuleGroupBatched(ctx, obj.ModuleGroupID)
}

// OrgUnit is the resolver for the orgUnit field.
func (r *modulePropagationResolver) OrgUnit(ctx context.Context, obj *models.ModulePropagation) (*models.OrgUnit, error) {
	return r.apiClient.GetOrgUnitBatched(ctx, obj.OrgUnitID)
}

// OrgDimension is the resolver for the orgDimension field.
func (r *modulePropagationResolver) OrgDimension(ctx context.Context, obj *models.ModulePropagation) (*models.OrgDimension, error) {
	return r.apiClient.GetOrgDimensionBatched(ctx, obj.OrgDimensionID)
}

// ModuleAssignments is the resolver for the moduleAssignments field.
func (r *modulePropagationResolver) ModuleAssignments(ctx context.Context, obj *models.ModulePropagation, filters *models.ModuleAssignmentFilters, limit *int, offset *int) ([]*models.ModuleAssignment, error) {
	return r.apiClient.GetModuleAssignmentsForModulePropagation(ctx, obj.ID, filters, limit, offset)
}

// ExecutionRequests is the resolver for the executionRequests field.
func (r *modulePropagationResolver) ExecutionRequests(ctx context.Context, obj *models.ModulePropagation, filters *models.ModulePropagationExecutionRequestFilters, limit *int, offset *int) ([]*models.ModulePropagationExecutionRequest, error) {
	return r.apiClient.GetModulePropagationExecutionRequestsForModulePropagation(ctx, obj.ID, filters, limit, offset)
}

// DriftCheckRequests is the resolver for the driftCheckRequests field.
func (r *modulePropagationResolver) DriftCheckRequests(ctx context.Context, obj *models.ModulePropagation, filters *models.ModulePropagationDriftCheckRequestFilters, limit *int, offset *int) ([]*models.ModulePropagationDriftCheckRequest, error) {
	return r.apiClient.GetModulePropagationDriftCheckRequestsForModulePropagation(ctx, obj.ID, filters, limit, offset)
}

// CreateModulePropagation is the resolver for the createModulePropagation field.
func (r *mutationResolver) CreateModulePropagation(ctx context.Context, modulePropagation models.NewModulePropagation) (*models.ModulePropagation, error) {
	return r.apiClient.CreateModulePropagation(ctx, &modulePropagation)
}

// DeleteModulePropagation is the resolver for the deleteModulePropagation field.
func (r *mutationResolver) DeleteModulePropagation(ctx context.Context, modulePropagationID uint) (bool, error) {
	err := r.apiClient.DeleteModulePropagation(ctx, modulePropagationID)
	return err == nil, err
}

// UpdateModulePropagation is the resolver for the updateModulePropagation field.
func (r *mutationResolver) UpdateModulePropagation(ctx context.Context, modulePropagationID uint, update models.ModulePropagationUpdate) (*models.ModulePropagation, error) {
	return r.apiClient.UpdateModulePropagation(ctx, modulePropagationID, &update)
}

// ModulePropagation is the resolver for the modulePropagation field.
func (r *queryResolver) ModulePropagation(ctx context.Context, modulePropagationID uint) (*models.ModulePropagation, error) {
	return r.apiClient.GetModulePropagation(ctx, modulePropagationID)
}

// ModulePropagations is the resolver for the modulePropagations field.
func (r *queryResolver) ModulePropagations(ctx context.Context, filters *models.ModulePropagationFilters, limit *int, offset *int) ([]*models.ModulePropagation, error) {
	return r.apiClient.GetModulePropagations(ctx, filters, limit, offset)
}

// ModulePropagation returns generated.ModulePropagationResolver implementation.
func (r *Resolver) ModulePropagation() generated.ModulePropagationResolver {
	return &modulePropagationResolver{r}
}

type modulePropagationResolver struct{ *Resolver }
