package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.22

import (
	"context"

	"github.com/sheacloud/tfom/internal/graph/generated"
	"github.com/sheacloud/tfom/pkg/models"
)

// ModulePropagation is the resolver for the modulePropagation field.
func (r *modulePropagationAssignmentResolver) ModulePropagation(ctx context.Context, obj *models.ModulePropagationAssignment) (*models.ModulePropagation, error) {
	return r.apiClient.GetModulePropagationBatched(ctx, obj.ModulePropagationId)
}

// OrgAccount is the resolver for the orgAccount field.
func (r *modulePropagationAssignmentResolver) OrgAccount(ctx context.Context, obj *models.ModulePropagationAssignment) (*models.OrganizationalAccount, error) {
	return r.apiClient.GetOrganizationalAccountBatched(ctx, obj.OrgAccountId)
}

// ModuleAssignment is the resolver for the moduleAssignment field.
func (r *modulePropagationAssignmentResolver) ModuleAssignment(ctx context.Context, obj *models.ModulePropagationAssignment) (*models.ModuleAssignment, error) {
	return r.apiClient.GetModuleAssignmentBatched(ctx, obj.ModuleAssignmentId)
}

// ModulePropagationAssignment returns generated.ModulePropagationAssignmentResolver implementation.
func (r *Resolver) ModulePropagationAssignment() generated.ModulePropagationAssignmentResolver {
	return &modulePropagationAssignmentResolver{r}
}

type modulePropagationAssignmentResolver struct{ *Resolver }
