package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.22

import (
	"context"

	"github.com/sheacloud/tfom/internal/graph/generated"
	"github.com/sheacloud/tfom/pkg/models"
)

// ModulePropagation is the resolver for the modulePropagation field.
func (r *modulePropagationDriftCheckRequestResolver) ModulePropagation(ctx context.Context, obj *models.ModulePropagationDriftCheckRequest) (*models.ModulePropagation, error) {
	return r.apiClient.GetModulePropagationBatched(ctx, obj.ModulePropagationID)
}

// TerraformDriftCheckRequests is the resolver for the terraformDriftCheckRequests field.
func (r *modulePropagationDriftCheckRequestResolver) TerraformDriftCheckRequests(ctx context.Context, obj *models.ModulePropagationDriftCheckRequest, filters *models.TerraformDriftCheckRequestFilters, limit *int, offset *int) ([]*models.TerraformDriftCheckRequest, error) {
	return r.apiClient.GetTerraformDriftCheckRequestsForModulePropagationDriftCheckRequest(ctx, obj.ID, filters, limit, offset)
}

// CreateModulePropagationDriftCheckRequest is the resolver for the createModulePropagationDriftCheckRequest field.
func (r *mutationResolver) CreateModulePropagationDriftCheckRequest(ctx context.Context, modulePropagationDriftCheckRequest models.NewModulePropagationDriftCheckRequest) (*models.ModulePropagationDriftCheckRequest, error) {
	return r.apiClient.CreateModulePropagationDriftCheckRequest(ctx, &modulePropagationDriftCheckRequest)
}

// ModulePropagationDriftCheckRequest is the resolver for the modulePropagationDriftCheckRequest field.
func (r *queryResolver) ModulePropagationDriftCheckRequest(ctx context.Context, modulePropagationDriftCheckRequestID uint) (*models.ModulePropagationDriftCheckRequest, error) {
	return r.apiClient.GetModulePropagationDriftCheckRequest(ctx, modulePropagationDriftCheckRequestID)
}

// ModulePropagationDriftCheckRequests is the resolver for the modulePropagationDriftCheckRequests field.
func (r *queryResolver) ModulePropagationDriftCheckRequests(ctx context.Context, filters *models.ModulePropagationDriftCheckRequestFilters, limit *int, offset *int) ([]*models.ModulePropagationDriftCheckRequest, error) {
	return r.apiClient.GetModulePropagationDriftCheckRequests(ctx, filters, limit, offset)
}

// ModulePropagationDriftCheckRequest returns generated.ModulePropagationDriftCheckRequestResolver implementation.
func (r *Resolver) ModulePropagationDriftCheckRequest() generated.ModulePropagationDriftCheckRequestResolver {
	return &modulePropagationDriftCheckRequestResolver{r}
}

type modulePropagationDriftCheckRequestResolver struct{ *Resolver }
