package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.22

import (
	"context"

	"github.com/aws/aws-sdk-go-v2/aws"
	"github.com/sheacloud/tfom/internal/graph/generated"
	"github.com/sheacloud/tfom/pkg/models"
)

// CreateOrganizationalUnitMembership is the resolver for the createOrganizationalUnitMembership field.
func (r *mutationResolver) CreateOrganizationalUnitMembership(ctx context.Context, orgUnitMembership models.NewOrganizationalUnitMembership) (*models.OrganizationalUnitMembership, error) {
	return r.apiClient.PutOrganizationalUnitMembership(ctx, &orgUnitMembership)
}

// DeleteOrganizationalUnitMembership is the resolver for the deleteOrganizationalUnitMembership field.
func (r *mutationResolver) DeleteOrganizationalUnitMembership(ctx context.Context, orgDimensionID string, orgAccountID string) (bool, error) {
	err := r.apiClient.DeleteOrganizationalUnitMembership(ctx, orgDimensionID, orgAccountID)
	return err == nil, err
}

// OrgAccount is the resolver for the orgAccount field.
func (r *organizationalUnitMembershipResolver) OrgAccount(ctx context.Context, obj *models.OrganizationalUnitMembership) (*models.OrganizationalAccount, error) {
	return r.apiClient.GetOrganizationalAccount(ctx, obj.OrgAccountId)
}

// OrgUnit is the resolver for the orgUnit field.
func (r *organizationalUnitMembershipResolver) OrgUnit(ctx context.Context, obj *models.OrganizationalUnitMembership) (*models.OrganizationalUnit, error) {
	return r.apiClient.GetOrganizationalUnit(ctx, obj.OrgDimensionId, obj.OrgUnitId)
}

// OrgDimension is the resolver for the orgDimension field.
func (r *organizationalUnitMembershipResolver) OrgDimension(ctx context.Context, obj *models.OrganizationalUnitMembership) (*models.OrganizationalDimension, error) {
	return r.apiClient.GetOrganizationalDimension(ctx, obj.OrgDimensionId)
}

// OrganizationalUnitMembershipsByOrgDimension is the resolver for the organizationalUnitMembershipsByOrgDimension field.
func (r *queryResolver) OrganizationalUnitMembershipsByOrgDimension(ctx context.Context, orgDimensionID string, limit *int, nextCursor *string) (*models.OrganizationalUnitMemberships, error) {
	if limit == nil {
		limit = aws.Int(100)
	}
	return r.apiClient.GetOrganizationalUnitMembershipsByDimension(ctx, orgDimensionID, int32(*limit), aws.ToString(nextCursor))
}

// OrganizationalUnitMembershipsByOrgAccount is the resolver for the organizationalUnitMembershipsByOrgAccount field.
func (r *queryResolver) OrganizationalUnitMembershipsByOrgAccount(ctx context.Context, orgAccountID string, limit *int, nextCursor *string) (*models.OrganizationalUnitMemberships, error) {
	if limit == nil {
		limit = aws.Int(100)
	}
	return r.apiClient.GetOrganizationalUnitMembershipsByAccount(ctx, orgAccountID, int32(*limit), aws.ToString(nextCursor))
}

// OrganizationalUnitMembershipsByOrgUnit is the resolver for the organizationalUnitMembershipsByOrgUnit field.
func (r *queryResolver) OrganizationalUnitMembershipsByOrgUnit(ctx context.Context, orgUnitID string, limit *int, nextCursor *string) (*models.OrganizationalUnitMemberships, error) {
	if limit == nil {
		limit = aws.Int(100)
	}
	return r.apiClient.GetOrganizationalUnitMembershipsByOrgUnit(ctx, orgUnitID, int32(*limit), aws.ToString(nextCursor))
}

// OrganizationalUnitMembership returns generated.OrganizationalUnitMembershipResolver implementation.
func (r *Resolver) OrganizationalUnitMembership() generated.OrganizationalUnitMembershipResolver {
	return &organizationalUnitMembershipResolver{r}
}

type organizationalUnitMembershipResolver struct{ *Resolver }
