package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.22

import (
	"context"

	"github.com/sheacloud/tfom/internal/graph/generated"
	"github.com/sheacloud/tfom/pkg/models"
)

// ModuleAssignment is the resolver for the moduleAssignment field.
func (r *planExecutionRequestResolver) ModuleAssignment(ctx context.Context, obj *models.PlanExecutionRequest) (*models.ModuleAssignment, error) {
	return r.apiClient.GetModuleAssignmentBatched(ctx, obj.ModuleAssignmentID)
}

// InitOutput is the resolver for the initOutput field.
func (r *planExecutionRequestResolver) InitOutput(ctx context.Context, obj *models.PlanExecutionRequest) (*string, error) {
	response := string(obj.InitOutput)
	return &response, nil
}

// PlanOutput is the resolver for the planOutput field.
func (r *planExecutionRequestResolver) PlanOutput(ctx context.Context, obj *models.PlanExecutionRequest) (*string, error) {
	response := string(obj.PlanOutput)
	return &response, nil
}

// PlanFile is the resolver for the planFile field.
func (r *planExecutionRequestResolver) PlanFile(ctx context.Context, obj *models.PlanExecutionRequest) (*string, error) {
	response := string(obj.PlanFile)
	return &response, nil
}

// PlanJSON is the resolver for the planJSON field.
func (r *planExecutionRequestResolver) PlanJSON(ctx context.Context, obj *models.PlanExecutionRequest) (*string, error) {
	response := string(obj.PlanJSON)
	return &response, nil
}

// PlanExecutionRequest is the resolver for the planExecutionRequest field.
func (r *queryResolver) PlanExecutionRequest(ctx context.Context, planExecutionRequestID uint) (*models.PlanExecutionRequest, error) {
	return r.apiClient.GetPlanExecutionRequest(ctx, planExecutionRequestID)
}

// PlanExecutionRequest returns generated.PlanExecutionRequestResolver implementation.
func (r *Resolver) PlanExecutionRequest() generated.PlanExecutionRequestResolver {
	return &planExecutionRequestResolver{r}
}

type planExecutionRequestResolver struct{ *Resolver }
