package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.22

import (
	"context"
	"fmt"

	"github.com/aws/aws-sdk-go-v2/aws"
	"github.com/sheacloud/tfom/internal/graph/generated"
	"github.com/sheacloud/tfom/pkg/models"
)

// ModuleAssignment is the resolver for the moduleAssignment field.
func (r *planExecutionRequestResolver) ModuleAssignment(ctx context.Context, obj *models.PlanExecutionRequest) (*models.ModuleAssignment, error) {
	panic(fmt.Errorf("not implemented: ModuleAssignment - moduleAssignment"))
}

// PlanExecutionRequest is the resolver for the planExecutionRequest field.
func (r *queryResolver) PlanExecutionRequest(ctx context.Context, planExecutionRequestID string, withOutputs *bool) (*models.PlanExecutionRequest, error) {
	return r.apiClient.GetPlanExecutionRequest(ctx, planExecutionRequestID, aws.ToBool(withOutputs))
}

// PlanExecutionRequests is the resolver for the planExecutionRequests field.
func (r *queryResolver) PlanExecutionRequests(ctx context.Context, limit *int, nextCursor *string, withOutputs *bool) (*models.PlanExecutionRequests, error) {
	if limit == nil {
		limit = aws.Int(100)
	}

	return r.apiClient.GetPlanExecutionRequests(ctx, int32(*limit), aws.ToString(nextCursor), aws.ToBool(withOutputs))
}

// PlanExecutionRequest returns generated.PlanExecutionRequestResolver implementation.
func (r *Resolver) PlanExecutionRequest() generated.PlanExecutionRequestResolver {
	return &planExecutionRequestResolver{r}
}

type planExecutionRequestResolver struct{ *Resolver }
