package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.22

import (
	"context"

	"github.com/aws/aws-sdk-go-v2/aws"
	"github.com/sheacloud/tfom/internal/graph/generated"
	"github.com/sheacloud/tfom/pkg/models"
)

// CreateTerraformExecutionRequest is the resolver for the createTerraformExecutionRequest field.
func (r *mutationResolver) CreateTerraformExecutionRequest(ctx context.Context, terraformExecutionRequest models.NewTerraformExecutionRequest) (*models.TerraformExecutionRequest, error) {
	return r.apiClient.PutTerraformExecutionRequest(ctx, &terraformExecutionRequest)
}

// ModuleAssignment is the resolver for the moduleAssignment field.
func (r *terraformExecutionRequestResolver) ModuleAssignment(ctx context.Context, obj *models.TerraformExecutionRequest) (*models.ModuleAssignment, error) {
	return r.apiClient.GetModuleAssignment(ctx, obj.ModuleAssignmentId)
}

// PlanExecutionRequest is the resolver for the planExecutionRequest field.
func (r *terraformExecutionRequestResolver) PlanExecutionRequest(ctx context.Context, obj *models.TerraformExecutionRequest, withOutputs *bool) (*models.PlanExecutionRequest, error) {
	if obj.PlanExecutionRequestId == nil {
		return nil, nil
	}
	return r.apiClient.GetPlanExecutionRequest(ctx, *obj.PlanExecutionRequestId, aws.ToBool(withOutputs))
}

// ApplyExecutionRequest is the resolver for the applyExecutionRequest field.
func (r *terraformExecutionRequestResolver) ApplyExecutionRequest(ctx context.Context, obj *models.TerraformExecutionRequest, withOutputs *bool) (*models.ApplyExecutionRequest, error) {
	if obj.ApplyExecutionRequestId == nil {
		return nil, nil
	}
	return r.apiClient.GetApplyExecutionRequest(ctx, *obj.ApplyExecutionRequestId, aws.ToBool(withOutputs))
}

// ModulePropagation is the resolver for the modulePropagation field.
func (r *terraformExecutionRequestResolver) ModulePropagation(ctx context.Context, obj *models.TerraformExecutionRequest) (*models.ModulePropagation, error) {
	if obj.ModulePropagationId == nil {
		return nil, nil
	}
	return r.apiClient.GetModulePropagation(ctx, *obj.ModulePropagationId)
}

// ModulePropagationExecutionRequest is the resolver for the modulePropagationExecutionRequest field.
func (r *terraformExecutionRequestResolver) ModulePropagationExecutionRequest(ctx context.Context, obj *models.TerraformExecutionRequest) (*models.ModulePropagationExecutionRequest, error) {
	if obj.ModulePropagationId == nil || obj.ModulePropagationExecutionRequestId == nil {
		return nil, nil
	}
	return r.apiClient.GetModulePropagationExecutionRequest(ctx, *obj.ModulePropagationId, *obj.ModulePropagationExecutionRequestId)
}

// TerraformExecutionRequest returns generated.TerraformExecutionRequestResolver implementation.
func (r *Resolver) TerraformExecutionRequest() generated.TerraformExecutionRequestResolver {
	return &terraformExecutionRequestResolver{r}
}

type terraformExecutionRequestResolver struct{ *Resolver }
