package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.22

import (
	"context"

	"github.com/sheacloud/tfom/internal/graph/generated"
	"github.com/sheacloud/tfom/pkg/models"
)

// CreateTerraformExecutionWorkflowRequest is the resolver for the createTerraformExecutionWorkflowRequest field.
func (r *mutationResolver) CreateTerraformExecutionWorkflowRequest(ctx context.Context, terraformExecutionWorkflowRequest models.NewTerraformExecutionWorkflowRequest) (*models.TerraformExecutionWorkflowRequest, error) {
	return r.apiClient.PutTerraformExecutionWorkflowRequest(ctx, &terraformExecutionWorkflowRequest)
}

// ModuleAssignment is the resolver for the moduleAssignment field.
func (r *terraformExecutionWorkflowRequestResolver) ModuleAssignment(ctx context.Context, obj *models.TerraformExecutionWorkflowRequest) (*models.ModuleAssignment, error) {
	return r.apiClient.GetModuleAssignment(ctx, obj.ModuleAssignmentId)
}

// PlanExecutionRequest is the resolver for the planExecutionRequest field.
func (r *terraformExecutionWorkflowRequestResolver) PlanExecutionRequest(ctx context.Context, obj *models.TerraformExecutionWorkflowRequest) (*models.PlanExecutionRequest, error) {
	if obj.PlanExecutionRequestId == nil {
		return nil, nil
	}
	return r.apiClient.GetPlanExecutionRequest(ctx, *obj.PlanExecutionRequestId)
}

// ApplyExecutionRequest is the resolver for the applyExecutionRequest field.
func (r *terraformExecutionWorkflowRequestResolver) ApplyExecutionRequest(ctx context.Context, obj *models.TerraformExecutionWorkflowRequest) (*models.ApplyExecutionRequest, error) {
	if obj.ApplyExecutionRequestId == nil {
		return nil, nil
	}
	return r.apiClient.GetApplyExecutionRequest(ctx, *obj.ApplyExecutionRequestId)
}

// ModulePropagation is the resolver for the modulePropagation field.
func (r *terraformExecutionWorkflowRequestResolver) ModulePropagation(ctx context.Context, obj *models.TerraformExecutionWorkflowRequest) (*models.ModulePropagation, error) {
	if obj.ModulePropagationId == nil {
		return nil, nil
	}
	return r.apiClient.GetModulePropagation(ctx, *obj.ModulePropagationId)
}

// ModulePropagationExecutionRequest is the resolver for the modulePropagationExecutionRequest field.
func (r *terraformExecutionWorkflowRequestResolver) ModulePropagationExecutionRequest(ctx context.Context, obj *models.TerraformExecutionWorkflowRequest) (*models.ModulePropagationExecutionRequest, error) {
	if obj.ModulePropagationId == nil || obj.ModulePropagationExecutionRequestId == nil {
		return nil, nil
	}
	return r.apiClient.GetModulePropagationExecutionRequest(ctx, *obj.ModulePropagationId, *obj.ModulePropagationExecutionRequestId)
}

// TerraformExecutionWorkflowRequest returns generated.TerraformExecutionWorkflowRequestResolver implementation.
func (r *Resolver) TerraformExecutionWorkflowRequest() generated.TerraformExecutionWorkflowRequestResolver {
	return &terraformExecutionWorkflowRequestResolver{r}
}

type terraformExecutionWorkflowRequestResolver struct{ *Resolver }
