package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.22

import (
	"context"

	"github.com/sheacloud/tfom/internal/graph/generated"
	"github.com/sheacloud/tfom/pkg/models"
)

// ModulePropagationDriftCheckRequest is the resolver for the modulePropagationDriftCheckRequest field.
func (r *terraformDriftCheckWorkflowRequestResolver) ModulePropagationDriftCheckRequest(ctx context.Context, obj *models.TerraformDriftCheckWorkflowRequest) (*models.ModulePropagationDriftCheckRequest, error) {
	modulePropagationId, err := r.ModulePropagationID(ctx, obj)
	if err != nil {
		return nil, err
	}
	return r.apiClient.GetModulePropagationDriftCheckRequest(ctx, modulePropagationId, obj.ModulePropagationDriftCheckRequestId)
}

// ModuleAccountAssociation is the resolver for the moduleAccountAssociation field.
func (r *terraformDriftCheckWorkflowRequestResolver) ModuleAccountAssociation(ctx context.Context, obj *models.TerraformDriftCheckWorkflowRequest) (*models.ModuleAccountAssociation, error) {
	key, err := models.ParseModuleAccountAssociationKey(obj.ModuleAccountAssociationKey)
	if err != nil {
		return nil, err
	}
	return r.apiClient.GetModuleAccountAssociation(ctx, key.ModulePropagationId, key.OrgAccountId)
}

// OrgAccountID is the resolver for the orgAccountId field.
func (r *terraformDriftCheckWorkflowRequestResolver) OrgAccountID(ctx context.Context, obj *models.TerraformDriftCheckWorkflowRequest) (string, error) {
	key, err := models.ParseModuleAccountAssociationKey(obj.ModuleAccountAssociationKey)
	if err != nil {
		return "", err
	}
	return key.OrgAccountId, nil
}

// OrgAccount is the resolver for the orgAccount field.
func (r *terraformDriftCheckWorkflowRequestResolver) OrgAccount(ctx context.Context, obj *models.TerraformDriftCheckWorkflowRequest) (*models.OrganizationalAccount, error) {
	orgAccountId, err := r.OrgAccountID(ctx, obj)
	if err != nil {
		return nil, err
	}
	return r.apiClient.GetOrganizationalAccount(ctx, orgAccountId)
}

// ModulePropagationID is the resolver for the modulePropagationId field.
func (r *terraformDriftCheckWorkflowRequestResolver) ModulePropagationID(ctx context.Context, obj *models.TerraformDriftCheckWorkflowRequest) (string, error) {
	key, err := models.ParseModuleAccountAssociationKey(obj.ModuleAccountAssociationKey)
	if err != nil {
		return "", err
	}
	return key.ModulePropagationId, nil
}

// ModulePropagation is the resolver for the modulePropagation field.
func (r *terraformDriftCheckWorkflowRequestResolver) ModulePropagation(ctx context.Context, obj *models.TerraformDriftCheckWorkflowRequest) (*models.ModulePropagation, error) {
	modulePropagationId, err := r.ModulePropagationID(ctx, obj)
	if err != nil {
		return nil, err
	}
	return r.apiClient.GetModulePropagation(ctx, modulePropagationId)
}

// PlanExecutionRequest is the resolver for the planExecutionRequest field.
func (r *terraformDriftCheckWorkflowRequestResolver) PlanExecutionRequest(ctx context.Context, obj *models.TerraformDriftCheckWorkflowRequest) (*models.PlanExecutionRequest, error) {
	if obj.PlanExecutionRequestId == nil {
		return nil, nil
	}
	return r.apiClient.GetPlanExecutionRequest(ctx, *obj.PlanExecutionRequestId)
}

// TerraformDriftCheckWorkflowRequest returns generated.TerraformDriftCheckWorkflowRequestResolver implementation.
func (r *Resolver) TerraformDriftCheckWorkflowRequest() generated.TerraformDriftCheckWorkflowRequestResolver {
	return &terraformDriftCheckWorkflowRequestResolver{r}
}

type terraformDriftCheckWorkflowRequestResolver struct{ *Resolver }
