package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.22

import (
	"context"

	"github.com/sheacloud/tfom/internal/graph/generated"
	"github.com/sheacloud/tfom/pkg/models"
)

// CreateTerraformExecutionRequest is the resolver for the createTerraformExecutionRequest field.
func (r *mutationResolver) CreateTerraformExecutionRequest(ctx context.Context, terraformExecutionRequest models.NewTerraformExecutionRequest) (*models.TerraformExecutionRequest, error) {
	return r.apiClient.CreateTerraformExecutionRequest(ctx, &terraformExecutionRequest)
}

// ModuleAssignment is the resolver for the moduleAssignment field.
func (r *terraformExecutionRequestResolver) ModuleAssignment(ctx context.Context, obj *models.TerraformExecutionRequest) (*models.ModuleAssignment, error) {
	return r.apiClient.GetModuleAssignmentBatched(ctx, obj.ModuleAssignmentID)
}

// PlanExecutionRequest is the resolver for the planExecutionRequest field.
func (r *terraformExecutionRequestResolver) PlanExecutionRequest(ctx context.Context, obj *models.TerraformExecutionRequest) (*models.PlanExecutionRequest, error) {
	return r.apiClient.GetPlanExecutionRequestForTerraformExecutionRequest(ctx, obj.ID)
}

// ApplyExecutionRequest is the resolver for the applyExecutionRequest field.
func (r *terraformExecutionRequestResolver) ApplyExecutionRequest(ctx context.Context, obj *models.TerraformExecutionRequest) (*models.ApplyExecutionRequest, error) {
	return r.apiClient.GetApplyExecutionRequestForTerraformExecutionRequest(ctx, obj.ID)
}

// ModulePropagation is the resolver for the modulePropagation field.
func (r *terraformExecutionRequestResolver) ModulePropagation(ctx context.Context, obj *models.TerraformExecutionRequest) (*models.ModulePropagation, error) {
	if obj.ModulePropagationID == nil {
		return nil, nil
	}
	return r.apiClient.GetModulePropagationBatched(ctx, *obj.ModulePropagationID)
}

// ModulePropagationExecutionRequest is the resolver for the modulePropagationExecutionRequest field.
func (r *terraformExecutionRequestResolver) ModulePropagationExecutionRequest(ctx context.Context, obj *models.TerraformExecutionRequest) (*models.ModulePropagationExecutionRequest, error) {
	if obj.ModulePropagationExecutionRequestID == nil {
		return nil, nil
	}
	return r.apiClient.GetModulePropagationExecutionRequestBatched(ctx, *obj.ModulePropagationExecutionRequestID)
}

// TerraformExecutionRequest returns generated.TerraformExecutionRequestResolver implementation.
func (r *Resolver) TerraformExecutionRequest() generated.TerraformExecutionRequestResolver {
	return &terraformExecutionRequestResolver{r}
}

type terraformExecutionRequestResolver struct{ *Resolver }
