package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.22

import (
	"context"

	"github.com/sheacloud/tfom/internal/graph/generated"
	"github.com/sheacloud/tfom/pkg/models"
)

// ModuleAssignment is the resolver for the moduleAssignment field.
func (r *terraformDriftCheckWorkflowRequestResolver) ModuleAssignment(ctx context.Context, obj *models.TerraformDriftCheckWorkflowRequest) (*models.ModuleAssignment, error) {
	return r.apiClient.GetModuleAssignment(ctx, obj.ModuleAssignmentId)
}

// PlanExecutionRequest is the resolver for the planExecutionRequest field.
func (r *terraformDriftCheckWorkflowRequestResolver) PlanExecutionRequest(ctx context.Context, obj *models.TerraformDriftCheckWorkflowRequest) (*models.PlanExecutionRequest, error) {
	if obj.PlanExecutionRequestId == nil {
		return nil, nil
	}
	return r.apiClient.GetPlanExecutionRequest(ctx, *obj.PlanExecutionRequestId)
}

// ModulePropagation is the resolver for the modulePropagation field.
func (r *terraformDriftCheckWorkflowRequestResolver) ModulePropagation(ctx context.Context, obj *models.TerraformDriftCheckWorkflowRequest) (*models.ModulePropagation, error) {
	if obj.ModulePropagationId == nil {
		return nil, nil
	}
	return r.apiClient.GetModulePropagation(ctx, *obj.ModulePropagationId)
}

// ModulePropagationDriftCheckRequest is the resolver for the modulePropagationDriftCheckRequest field.
func (r *terraformDriftCheckWorkflowRequestResolver) ModulePropagationDriftCheckRequest(ctx context.Context, obj *models.TerraformDriftCheckWorkflowRequest) (*models.ModulePropagationDriftCheckRequest, error) {
	if obj.ModulePropagationId == nil || obj.ModulePropagationDriftCheckRequestId == nil {
		return nil, nil
	}
	return r.apiClient.GetModulePropagationDriftCheckRequest(ctx, *obj.ModulePropagationId, *obj.ModulePropagationDriftCheckRequestId)
}

// TerraformDriftCheckWorkflowRequest returns generated.TerraformDriftCheckWorkflowRequestResolver implementation.
func (r *Resolver) TerraformDriftCheckWorkflowRequest() generated.TerraformDriftCheckWorkflowRequestResolver {
	return &terraformDriftCheckWorkflowRequestResolver{r}
}

type terraformDriftCheckWorkflowRequestResolver struct{ *Resolver }
